In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [2]:
arr = np.array([1.2, 'viraj', 4.0])
arr

array(['1.2', 'viraj', '4.0'], dtype='<U32')

In [5]:
arr = np.array([1.2, 1+2j, 4.0])
arr

array([1.2+0.j, 1. +2.j, 4. +0.j])

In [6]:
arr = np.array([1.2, 24.5, 4.0])
arr

array([ 1.2, 24.5,  4. ])

# map

In [16]:
list1 = [3,6,8]
list(map(str, list1))
list(map(lambda x:x%2, list1))

[1, 0, 0]

# filter

In [13]:
tuple(filter(lambda x:x%3==0, list1))

(3, 6)

In [19]:
list(filter(None, ["ash", "", "ashgf"]))

['ash', 'ashgf']

In [25]:
list(filter(lambda x:x.isspace(), ["ash", " ", "ashgf"]))

[' ']

# boolean mask arrays

In [27]:
arr = np.array([0, -12, 21, 55, 49])
arr

array([  0, -12,  21,  55,  49])

In [28]:
bool_mask_arry_7 = (arr%7)==0     # with divisible by 7 and remainder 0
bool_mask_arry_7

array([ True, False,  True, False,  True])

In [30]:
# subarray
new_arr = arr[bool_mask_arry_7]
new_arr

array([ 0, 21, 49])

In [31]:
new_arr[new_arr>0]   # python operator

array([21, 49])

In [32]:
# numpy logical and operator
np.logical_and(bool_mask_arry_7, arr>0)

array([False, False,  True, False,  True])

# View and copy

In [14]:
mi_casa = np.array(np.arange(5, 20, 2))
mi_casa

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
# view (shallow copy)
su_casa = mi_casa.view()
su_casa

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
print(su_casa == mi_casa)
print(id(su_casa), id(mi_casa))

[ True  True  True  True  True  True  True  True]
2436765820768 2436765820768


In [22]:
mi_casa[0] = 100
su_casa

array([100,   7,   9,  11,  13,  15,  17,  19])

In [25]:
# deep copy
lu_casa = mi_casa.copy()

print(id(lu_casa), id(mi_casa))

2436819417328 2436765820768


In [26]:
lu_casa.dtype

dtype('int32')

In [27]:
lu_casa.size

8

In [28]:
lu_casa.shape

(8,)

In [29]:
lu_casa.itemsize                 # memory size 4 bytes

4

# insert delete

In [33]:
arr = np.array([[[2,3,4],
                 [5,6,7]],
              [[11,22,33],
              [55,66,77]]])

In [34]:
arr.shape

(2, 2, 3)

In [35]:
arr

array([[[ 2,  3,  4],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [38]:
np.insert(arr, 1, 444, axis=0)

array([[[  2,   3,   4],
        [  5,   6,   7]],

       [[444, 444, 444],
        [444, 444, 444]],

       [[ 11,  22,  33],
        [ 55,  66,  77]]])

In [39]:
np.insert(arr, 1, 444, axis=1)

array([[[  2,   3,   4],
        [444, 444, 444],
        [  5,   6,   7]],

       [[ 11,  22,  33],
        [444, 444, 444],
        [ 55,  66,  77]]])

In [40]:
np.insert(arr, 1, 444, axis=2)

array([[[  2, 444,   3,   4],
        [  5, 444,   6,   7]],

       [[ 11, 444,  22,  33],
        [ 55, 444,  66,  77]]])

In [43]:
# delete
d = np.empty(arr.shape)
np.copyto(d, arr)
d

array([[[ 2.,  3.,  4.],
        [ 5.,  6.,  7.]],

       [[11., 22., 33.],
        [55., 66., 77.]]])

In [44]:
np.delete(d, 1, axis=0)

array([[[2., 3., 4.],
        [5., 6., 7.]]])

In [45]:
np.delete(d, 1, axis=1)

array([[[ 2.,  3.,  4.]],

       [[11., 22., 33.]]])

In [46]:
np.delete(d, 1, axis=2)

array([[[ 2.,  4.],
        [ 5.,  7.]],

       [[11., 33.],
        [55., 77.]]])